import "./globals.css";
import React from "react";
import { JetBrains_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import Header from "@/components/Header";

const jetbrainsMono = JetBrains_Mono(
  {
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: "--font-jetbrainsMono",
  }
);


export const metadata = {
  title: "Food Online Order Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <React.StrictMode>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${jetbrainsMono.variable} min-h-screen `}
          >
              <Header/>
            {children}
          </body>
        </html>
      </ClerkProvider>
    </React.StrictMode>
  );
}
